### ISSUE TITLE
Problems compiling BlueCryptor with CommonCrypto

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/CommonCrypto#1]
When I try to swift build BlueCryptor on OSX, I get:

BlueCryptor/Packages/CommonCrypto-0.1.0/module.modulemap:18:12: error: header '/usr/include/CommonCrypto/CommonCrypto.h' not found
    header "/usr/include/CommonCrypto/CommonCrypto.h"
           ^
BlueCryptor/Sources/Digest.swift:21:9: error: could not build Objective-C module 'CommonCrypto'
        import CommonCrypto
               ^
...

BlueCryptor builds fine on Linux.

**Comment by billabt** [comment]
On OS X, you need to install Xcode Command Line Tools. The instructions are located here -> https://developer.apple.com/library/ios/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-WHAT_IS_THE_COMMAND_LINE_TOOLS_PACKAGE_

Alternatively, you can just type the following from the command line `xcode-select --install`

I'll update the README.md to reflect this.

**Comment by billabt** [comment]
Fixed in 0.1.8 of _BlueCryptor_.
